# Build
FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . . 
ENV BUILD=stage
RUN go build -o main main.go

# Run
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
COPY --from=builder /app/.env .
COPY --from=builder /app/templates ./templates
EXPOSE 8000
CMD [ "/app/main" ]
